apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-agent-config
data:
  config.hcl: |
    auto_auth {
      method "kubernetes" {
        mount_path = "auth/kubernetes"
        config = {
          role = "general-app-role"
        }
      }
      sink "file" {
        config = {
          path = "/vault/secrets/configmap"
        }
      }
    }
    template {
      contents = <<EOH
      {
        {{- range $k, $v := .Data.data }}
        "{{ $k }}": "{{ $v }}",
        {{- end }}
      }
      EOH
      destination = "/vault/secrets/configmap"
    }
