apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJkb2NrZXIuaW8iOnsidXNlcm5hbWUiOiJhaXRvcHMiLCJwYXNzd29yZCI6ImRja3JfcGF0X1V4dUFhYnBBRDBJanlpMDhPdC1aVWtnZUJFVSIsImVtYWlsIjoiZGV2b3BzQGFrYXJpbnRpLnRlY2giLCJhdXRoIjoiWVdsMGIzQnpPbVJqYTNKZmNHRjBYMVY0ZFVGaFluQkJSREJKYW5scE1EaFBkQzFhVld0blpVSkZWUT09In19fQ==
kind: Secret
metadata:
  name: ait-registry-secret
type: kubernetes.io/dockerconfigjson
