apiVersion: v1
kind: Pod
metadata:
  name: kaniko
spec:
  containers:
    - name: kaniko
      image: gcr.io/kaniko-project/executor:latest
      resources:
        requests:
          cpu: "250m"
          memory: "256Mi"
        limits:
          cpu: "1000m"
          memory: "1024Mi"
      volumeMounts:
        - name: kaniko-secret
          mountPath: /kaniko/.docker
  nodeSelector:
    kubernetes.io/hostname:
      - virtual-kubelet-ap-southeast-5a
      - virtual-kubelet-ap-southeast-5b            
  tolerations:
    - key: virtual-kubelet.io/provider
      operator: Equal
      value: alibabacloud
      effect: NoSchedule
  volumes:
    - name: kaniko-secret
      secret:
        secretName: kaniko-registry-secret
