apiVersion: skaffold/v4beta11
kind: Config
build:
  artifacts:
    - image: aitops/tools
      kaniko:
        buildContext:
          localDir: {}
        cache: {}        
        dockerfile: Dockerfile
        logStreaming:
          enabled: true
        nodeSelector:
          kubernetes.io/hostname:
            - virtual-kubelet-ap-southeast-5a
            - virtual-kubelet-ap-southeast-5b            
        resources:
          requests:
            cpu: "250m"
            memory: "256Mi"          
          limits:
            cpu: "1000m"
            memory: "1024Mi" 
        tolerations:
        - key: virtual-kubelet.io/provider
          operator: Equal
          value: alibabacloud
          effect: NoSchedule
  cluster:
    dockerConfig:
      secretName: kaniko-registry-secret
  tagPolicy:
    gitCommit:
      prefix: test-
deploy:
  kubectl: {}
manifests:
  rawYaml:
    - ./k8s/*
