apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: reporookie
deploy:
  kubectl:
    manifests:
      - "./k8s/*"
build:
  tagPolicy:
    gitCommit:
      prefix: test-
  artifacts:
  - image: aitops/tools
    kaniko:
      buildContext:
        localDir: {}
      dockerfile: Dockerfile
  cluster: {}
#    namespace: test  # Specify the namespace if needed
#    pullSecretName: my-pull-secret  # Specify the pull secret if needed
#    serviceAccount: my-service-account  # Specify the service account if needed
