apiVersion: skaffold/v4beta11
kind: Config
build:
  artifacts:
    - image: aitops/tools
      kaniko:
        cache: {}        
        dockerfile: Dockerfile
  cluster:
    dockerConfig:
      secretName: kaniko-registry-secret
    nodeSelector:
      kubernetes.io/hostname:
        - virtual-kubelet-ap-southeast-5a
        - virtual-kubelet-ap-southeast-5b        
    tolerations:
    - key: virtual-kubelet.io/provider
      operator: Equal
      value: alibabacloud
      effect: NoSchedule    
  tagPolicy:
    gitCommit:
      prefix: test-
deploy:
  kubectl: {}
manifests:
  rawYaml:
    - ./k8s/dev/*
