apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: reporookie
deploy:
  kubectl:
    manifests:
      - "./k8s/*"
build:
  tagPolicy:
    gitCommit:
      prefix: test-
  artifacts:
  - image: aitops/tools
    kaniko:
      buildContext:
        localDir: {}
      dockerfile: Dockerfile
  cluster:
    tolerations:
    - key: virtual-kubelet.io/provider
      operator: Equal
      value: alibabacloud
      effect: NoSchedule
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
              - virtual-kubelet-ap-southeast-5a
              - virtual-kubelet-ap-southeast-5b
    volumes:
    - name: kaniko-secret
      secret:
        secretName: docker-registry-secret
    volumeMounts:
    - name: kaniko-secret
      mountPath: /kaniko/.docker
    env:
    - name: DOCKER_CONFIG
      value: /kaniko/.docker/        
#    namespace: test  # Specify the namespace if needed
#    pullSecretName: my-pull-secret  # Specify the pull secret if needed
#    serviceAccount: my-service-account  # Specify the service account if needed
