apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: reporookie
build:
  artifacts:
    - image: aitops/tools
      kaniko:
        dockerfile: Dockerfile
  tagPolicy:
    gitCommit:
      prefix: test-
  cluster:
    podSpec:
      terminationGracePeriodSeconds: 300
      containers:
      - name: kaniko
        lifecycle:
          preStop:
            exec:
              command: ["sh", "-c", "sleep 300"]
    tolerations:
    - key: virtual-kubelet.io/provider
      operator: Equal
      value: alibabacloud
      effect: NoSchedule
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
              - virtual-kubelet-ap-southeast-5a
              - virtual-kubelet-ap-southeast-5b
    volumes:
    - name: kaniko-secret
      secret:
        secretName: docker-registry-secret
    volumeMounts:
    - name: kaniko-secret
      mountPath: /kaniko/.docker
    env:
    - name: DOCKER_CONFIG
      value: /kaniko/.docker/        
manifests:
  rawYaml:
    - ./k8s/*
deploy:
  kubectl: {}
