apiVersion: skaffold/v4beta11
kind: Config
build:
  artifacts:
    - image: aitops/tools
      kaniko:
        buildContext:
          localDir: {}
        cache: {}        
        dockerfile: Dockerfile
        logStreaming:
          enabled: true
        podTemplate: ./k8s/pod-template/kaniko.yaml
  cluster: {}
  tagPolicy:
    gitCommit:
      prefix: test-
deploy:
  kubectl:
    logPrefix: kubectl
    logs:
      - container: kaniko
        driver: kubectl    
manifests:
  rawYaml:
    - ./k8s/dev/*
