apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: reporookie
build:
  tagPolicy:
    gitCommit:
      prefix: test-  
  artifacts:
  - image: aitops/tools
    kaniko:
      buildContext:
        localDir: {}
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
      - "./k8s/*"
