apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: reporookie
build:
  artifacts:
    - image: aitops/tools
      kaniko:
        dockerfile: Dockerfile
        pullSecretName: docker-registry-secret
  tagPolicy:
    gitCommit:
      prefix: test-
  cluster:
    tolerations:
    - key: virtual-kubelet.io/provider
      operator: Equal
      value: alibabacloud
      effect: NoSchedule
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
              - virtual-kubelet-ap-southeast-5a
              - virtual-kubelet-ap-southeast-5b
manifests:
  rawYaml:
    - ./k8s/*
deploy:
  kubectl: {}
