apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-agent-config
data:
  config.hcl: |
    auto_auth {
      method "kubernetes" {
        mount_path = "auth/kubernetes"
        config = {
          role = "general-app-role"
        }
      }
      sink "kubernetes" {
        config = {
          secret_name = "${AITPROJNAME}-secret"
          secret_namespace = "${AITNAMESPACE}"
          sync_period = "5m"
        }
      }
    }
  config-init.hcl: |
    auto_auth {
      method "kubernetes" {
        mount_path = "auth/kubernetes"
        config = {
          role = "general-app-role"
        }
      }
      sink "kubernetes" {
        config = {
          secret_name = "${AITPROJNAME}-secret"
          secret_namespace = "${AITNAMESPACE}"
          sync_period = "5m"
        }
      }
    }

