apiVersion: v1
kind: Pod
metadata:
  namespace: jenkins-agent  
  labels:
    jenkins: agent
spec:
  tolerations:
  - key: virtual-kubelet.io/provider
    operator: Equal
    value: alibabacloud
    effect: NoSchedule
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - virtual-kubelet-ap-southeast-5a
            - virtual-kubelet-ap-southeast-5b
  imagePullSecrets:
  - name: docker-registry-secret
  containers:
  - name: jnlp
    image: aitops/tools:skaffoldvaultsonar
    tty: true
    env:
    - name: KUBECONFIG
      value: /kubeconfig/kubeconfig
    - name: VAULT_TOKEN
      valueFrom:
        secretKeyRef:
          name: hashicorp-secret
          key: vault-token
    - name: SONAR_LOGIN
      valueFrom:
        secretKeyRef:
          name: sonarqube-secret
          key: sonar-token
    - name: VAULT_ADDR
      value: http://vault.vault.svc.cluster.local:8200
    - name: SONAR_HOST_URL
      value: http://sonarqube-sonarqube.sonarqube.svc.cluster.local:9000
    volumeMounts:
    - name: workspace
      mountPath: /home/jenkins/agent/workspace 
    - name: kubeconfig-secret
      mountPath: /kubeconfig
    resources:
      requests:
        cpu: "250m"
        memory: "256Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"
  - name: test
    image: ${AITTESTIMAGE} 
    tty: true
    volumeMounts:
    - name: workspace
      mountPath: /home/jenkins/agent/workspace 
    resources:
      requests:
        cpu: "500m"
        memory: "1Gi"
      limits:
        cpu: "1"
        memory: "2Gi"
  - name: dbtest
    image: ${AITDBTESTIMAGE} 
    tty: true
    volumeMounts:
    - name: workspace
      mountPath: /home/jenkins/agent/workspace 
    resources:
      requests:
        cpu: "500m"
        memory: "1Gi"
      limits:
        cpu: "1"
        memory: "2Gi"
  volumes:
  - name: kubeconfig-secret
    secret:
      secretName: kubeconfig-secret
  - name: workspace
    emptyDir: {}    
