apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: "${AITPROJNAME}-externalsecret"
  labels:
    app: ${AITGITCLIENT}
    service: ${AITGITSERVICE}
    ait.tech/${AITGITNAME}: ${AITGITBRANCH}
spec:
  secretStoreRef:
    name: akarintitech-clustersecretstore
    kind: ClusterSecretStore
  refreshInterval: "1h"
  target:
    name: ${AITPROJNAME}-secret
    creationPolicy: Orphan
    deletionPolicy: Delete
  dataFrom:
  - extract:
      key: akarintitech/${AITPROJNAME}
      conversionStrategy: Default
      decodingStrategy: None
